In [1]:
import pandas as pd
import numpy as np

In [2]:
data=pd.DataFrame({
    'Name': ['Alice','Bob',np.nan,'Daisy','Ethan'],
    'Age' :[25,np.nan,29,22,np.nan],
    'Salary' :[50000.0,60000.0,np.nan,5800.0,6200.0]
})

In [3]:
data

Name   Age   Salary
0  Alice  25.0  50000.0
1    Bob   NaN  60000.0
2    NaN  29.0      NaN
3  Daisy  22.0   5800.0
4  Ethan   NaN   6200.0

In [4]:
data_dropped=data.dropna()

In [5]:
data_dropped

Name   Age   Salary
0  Alice  25.0  50000.0
3  Daisy  22.0   5800.0

In [6]:
data

Name   Age   Salary
0  Alice  25.0  50000.0
1    Bob   NaN  60000.0
2    NaN  29.0      NaN
3  Daisy  22.0   5800.0
4  Ethan   NaN   6200.0

In [7]:
# preprocessing

data_filled=data.fillna({
    'Name': 'Unknown',
    'Age' : data['Age'].mean(),
    'Salary': 0
})

In [8]:
data_filled

Name        Age   Salary
0    Alice  25.000000  50000.0
1      Bob  25.333333  60000.0
2  Unknown  29.000000      0.0
3    Daisy  22.000000   5800.0
4    Ethan  25.333333   6200.0

In [13]:
array_main= np.array([[1,2,3],[4,5,6]])
print(array_main)

[[1 2 3]
 [4 5 6]]


In [14]:
print(array_main.shape)

(2, 3)


In [16]:
array_reshaped=array_main.reshape(3,2)
print(array_reshaped)

[[1 2]
 [3 4]
 [5 6]]


In [17]:
array_reshaped=array_main.reshape(1,6)
print(array_reshaped)

[[1 2 3 4 5 6]]


In [18]:
array_reshaped=array_main.reshape(6,1)
print(array_reshaped)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [19]:
# vertical stack
# harizontal stack
# depth stack

In [25]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,9]])

In [26]:
v_stacked=np.vstack([a,b])
print(v_stacked)

[[1 2]
 [3 4]
 [5 6]
 [7 9]]


In [29]:
h_stacked=np.hstack([a,b])
print(h_stacked)

[[1 2 5 6]
 [3 4 7 9]]


In [33]:
a=np.array([[3,2],[3,4]])
b=np.array([[5,6],[7,8]])
d_stacked=np.dstack([a,b])
print(d_stacked)

[[[3 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [35]:
a=np.array([[3,2]])
b=np.array([[5,6]])
d_stacked=np.dstack([a,b])
print(d_stacked)

[[[3 5]
  [2 6]]]


In [36]:
big_array=np.arange(10)
print(big_array)

[0 1 2 3 4 5 6 7 8 9]


In [37]:
split_array=np.split(big_array,2)
print(split_array)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]


In [38]:
split_array=np.split(big_array,3)
print(split_array)

ValueError: array split does not result in an equal division

In [40]:
print(type(split_array))

<class 'list'>


In [41]:
print(type(split_array[0]))

<class 'numpy.ndarray'>


In [43]:
sorted_array=np.array([10,20,30,40])
pos=np.searchsorted(sorted_array,25)

In [44]:
print(pos)

2


In [ ]:
# big_array=np.arange(10)
# print(big_array)

In [45]:
evens=np.where(big_array % 2==0)
print(evens)

(array([0, 2, 4, 6, 8]),)


In [46]:
print(type(evens))

<class 'tuple'>


In [47]:
print((evens[0]))

[0 2 4 6 8]


In [50]:
dummy_array=np.array([[1,2,3,4],[5,6,7,8]])

In [51]:
evens=np.where(dummy_array % 2==0)

In [52]:
print(evens)

(array([0, 0, 1, 1]), array([1, 3, 1, 3]))


In [57]:
sorted_data=data.sort_values(by='Salary',ascending=False)
print(sorted_data)

    Name   Age   Salary
1    Bob   NaN  60000.0
0  Alice  25.0  50000.0
4  Ethan   NaN   6200.0
3  Daisy  22.0   5800.0
2    NaN  29.0      NaN


In [56]:
sorted_data=data.sort_values(by='Salary',ascending=True)
print(sorted_data)

    Name   Age   Salary
3  Daisy  22.0   5800.0
4  Ethan   NaN   6200.0
0  Alice  25.0  50000.0
1    Bob   NaN  60000.0
2    NaN  29.0      NaN


In [58]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])

In [59]:
arr=np.concatenate([arr1,arr2])
print(arr)

[1 2 3 4 5 6]


In [60]:
arr1=np.array([[1,2,3],[6,8,3]])
arr2=np.array([[4,5,6],[2,5,6]])

In [61]:
arr=np.concatenate([arr1,arr2])
print(arr)

[[1 2 3]
 [6 8 3]
 [4 5 6]
 [2 5 6]]


In [62]:
arr=np.array([8,3,1,0])
print(np.sort(arr))

[0 1 3 8]


In [63]:
arr=np.array(['banana','cherry','apple'])
print(np.sort(arr))

['apple' 'banana' 'cherry']
