In [2]:
list1=[3,4,2]
list2=[2,4,2]

print(list1+list2)

[3, 4, 2, 2, 4, 2]


In [3]:
import numpy as np

In [4]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
print(arr1+arr2)

[5 7 9]


In [5]:
menu=np.array(['cheese','bbq','veg','spicy'])
print(menu)

['cheese' 'bbq' 'veg' 'spicy']


In [7]:
prices=np.array([100,200,150,220])
price=prices*0.8
print(price)

[ 80. 160. 120. 176.]


In [8]:
empty_table=np.zeros((2,3))
print(empty_table)

[[0. 0. 0.]
 [0. 0. 0.]]


In [11]:
full_table=np.ones((3,3))
print(full_table)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [13]:
bbq_boxes=np.full((2,3),'bbq')
print(bbq_boxes)

[['bbq' 'bbq' 'bbq']
 ['bbq' 'bbq' 'bbq']]


In [16]:
kids_order=np.random.randint(1,8,(2,3))
print(kids_order)

[[6 2 3]
 [5 1 4]]


In [18]:
surprise_toopings=np.random.rand(2,3)
print(surprise_toopings)

[[0.26440119 0.99105288 0.34240561]
 [0.29580372 0.74924756 0.31968723]]


In [19]:
signature_pizzas=np.identity(4)
print(signature_pizzas)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [20]:
delivery_times=np.arange(0,70,15)
print(delivery_times)

[ 0 15 30 45 60]


In [22]:
cooking_shifts=np.linspace(0,70,7)
print(cooking_shifts)

[ 0.         11.66666667 23.33333333 35.         46.66666667 58.33333333
 70.        ]


In [23]:
orders=np.array(['chesse','veg','spicy','bbq'])
print(orders[2])

spicy


In [26]:
print(orders[1:3])

['veg' 'spicy']


In [31]:
orders=np.array([[
    'cheese','veg'],
    ['spicy','bbq']])
print(orders)

[['cheese' 'veg']
 ['spicy' 'bbq']]


In [32]:
print(orders[1,0])

spicy


In [35]:
print(orders[:,0])


['cheese' 'spicy']


In [36]:
print(orders[:,1])

['veg' 'bbq']


In [38]:
orders=np.array([[
    'cheese','veg','veg'],
    ['spicy','bbq','spicy']])
print(orders)

[['cheese' 'veg' 'veg']
 ['spicy' 'bbq' 'spicy']]


In [39]:
print(orders[0,1:3])

['veg' 'veg']


In [40]:
print(orders[:,1:3])

[['veg' 'veg']
 ['bbq' 'spicy']]


In [41]:
sales=np.array([2000,1500,8000,3500])
print("Max sales index: ",np.argmax(sales))


Max sales index:  2


In [42]:
print("Max sales: ",np.max(sales))

Max sales:  8000


In [44]:
print("Min sales index: ",np.argmin(sales))

Min sales index:  1


In [46]:
print("Min sales: ",np.min(sales))

Min sales:  1500
